// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	UserId int64 `json:"userId"`
}

type UserResp struct {
	UserId int64  `json:"userId"`
	Name   string `json:"userName"`
}
